### ISSUE TITLE
How come binaries stopped being provided?

### ISSUE THREAD

**Issue by phlummox** [tfausak/github-release#14]
Hi, a query rather than a bug.

I notice that downloadable binaries stopped being provided in [April 2020][apr-2020] - I just wondered what the reason for this was? This seems to make the tool a good less convenient to use than the [Go tool][go-gh-release] [it was modelled on][fausak-blog].

cheers!

[apr-2020]: https://github.com/tfausak/github-release/commit/8c298a81fd3fa52772034d2c1d6ef3125e569138
[go-gh-release]: https://github.com/github-release/github-release
[fausak-blog]: https://taylor.fausak.me/2016/05/09/add-files-to-github-releases/

**Comment by tfausak** [comment]
Honestly I'm not sure. It definitely happened between versions [1.2.5 and 1.2.6](https://github.com/tfausak/github-release/compare/1.2.5...1.2.6), but I don't remember my motivation. I will add binaries back to the releases.

**Comment by phlummox** [comment]
Ha, no worries, I know the feeling :) Currently am looking at a test suite I wrote years ago for some app and wondering what on earth I was thinking..

**Comment by phlummox** [comment]
Cheers! Looking forward to using it in anger, so to speak :)
