### ISSUE TITLE
GitHub token should come from environment, not the command-line

### ISSUE THREAD

**Issue by pkgw** [tfausak/github-release#7]
I'd like to use this tool, but I'm a bit concerned about the way that the GitHub access token is passed in on the command line — I'd say that there's pretty broad consensus that this is a risky way to communicate secrets to a program, since command line parameters are often logged or visible to other users on a machine. (E.g., [relevant Azure Pipelines docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables).)

In this particular case, it's pretty common practice to store a GitHub token in the environment variable `$GITHUB_TOKEN`. Would you be willing to consider changing the program behavior to get the token this way, rather than as a command-line argument?

**Comment by tfausak** [comment]
Yeah, that seems reasonable. We could prefer to read from the `--token` option, but fall back to something like the `GITHUB_TOKEN` environment variable otherwise.
