### ISSUE TITLE
Add --replace or --force to upload sub-command

### ISSUE THREAD

**Issue by pbrisbin** [tfausak/github-release#8]
:point_up: if given, `upload` should not error when the uploaded artifact already exists on the given release, it should replace it.

Use case: In addition to releasing tagged versions (which I agree should always have immutable artifacts), I also like to let special tags (e.g. `master`) be updated with new artifacts from CI. In such a case, I would want to use `--replace` with the updated artifact.

**Comment by tfausak** [comment]
Since GitHub doesn't provide an easy way to overwrite assets, I went with the approach you suggested of adding a new `delete` command. You should be able to "replace" an asset by doing something like this:

``` sh
> github-release release --tag some-tag ...
> github-release delete --tag some-tag --name some-asset ... || true
> github-release upload --tag some-tag --name some-asset ...
```
